# Numpy ---> package / module


### POWERFUL N-DIMENSIONAL ARRAYS

Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.


### NUMERICAL COMPUTING TOOLS

NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

NumPy supports a wide range of hardware and computing platforms, and plays well with distributed, GPU, and sparse array libraries.

The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.

In [1]:
import numpy 
a = numpy.array([12,3.4,89])  #
print(a)

[12.   3.4 89. ]


In [3]:
import numpy 
a = numpy.array([12,3,89])  #
print(a)
print(a[0])
print(a[1])

[12  3 89]
12
3


In [5]:
import numpy
print(numpy.random.random())

0.9051849164059058


In [6]:
import numpy
print(numpy.random.random())

0.7720911328939231


In [7]:
import numpy
print(numpy.random.random())

0.9909393072040291


In [8]:
import numpy
print(numpy.random.random())

0.24161161420941069


In [12]:
a = [1,2,3]
b = [i**3  for i  in a]
print(a)
print(b)

[1, 2, 3]
[1, 8, 27]


In [13]:
a = range(100000)
%timeit [i**3  for i  in a]


201 ms ± 37.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
import numpy
a = numpy.array([1,2,3])
b = a ** 3
print(b)
print(a)

[ 1  8 27]
[1 2 3]


In [17]:
import numpy
a = range(100000)
a = numpy.array(a)
%timeit a ** 3


651 µs ± 23.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [18]:
import numpy
a = numpy.arange(100000)
%timeit a ** 3


712 µs ± 77.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
# Single numpy array
import numpy as np
a=np.array([1,2,3])  # 1 D
print(a)
print(a.ndim ,"D")
print(a.shape)

[1 2 3]
1 D
(3,)


In [24]:
# Two Dimentional numpy array
import numpy as np
a=np.array([[1,2,3],[9,4,5]])  # 2 D
print(a)
print(a.ndim ,"D")
print(a.shape)

[[1 2 3]
 [9 4 5]]
2 D
(2, 3)


In [27]:
# Three Dimentional numpy array
import numpy as np
a=np.array([[[1,2,3],[9,4,5]],[[1,2,3],[9,4,5]]])  # 3 D
print(a)
print(a.ndim ,"D")
print(a.shape)
print(type(a))

[[[1 2 3]
  [9 4 5]]

 [[1 2 3]
  [9 4 5]]]
3 D
(2, 2, 3)
<class 'numpy.ndarray'>


In [28]:
# four Dimentional numpy array
import numpy as np
a=np.array([[[[1,2,3],[9,4,5]],[[1,2,3],[9,4,5]]],[[[1,2,3],[9,4,5]],[[1,2,3],[9,4,5]]]])  # 4 D
print(a)
print(a.ndim ,"D")
print(a.shape)
print(type(a))

[[[[1 2 3]
   [9 4 5]]

  [[1 2 3]
   [9 4 5]]]


 [[[1 2 3]
   [9 4 5]]

  [[1 2 3]
   [9 4 5]]]]
4 D
(2, 2, 2, 3)
<class 'numpy.ndarray'>


In [29]:
# memory uses 

import numpy as np
import time
import sys
S= range(1000)  # S list 
print(sys.getsizeof(5)*len(S))
 
D= np.arange(1000) # Array
print(D.size*D.itemsize)

28000
4000


In [31]:
#speed 
import numpy
a = numpy.arange(100000)
%timeit a ** 3
a  = range(100000)
%timeit [i ** 3 for  i in a]

1.08 ms ± 190 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
162 ms ± 50.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [32]:
import numpy as np
a = np.array([(1,2,3)])
print(a.itemsize)

4


In [34]:
import numpy as np
a = np.array([(1,25.2,3)])
print(a.dtype)

float64


In [36]:
import numpy as np
a = np.array([(8,9,10),(11,12,13)])  # 2,3
print(a)
print(a.shape)
a=a.reshape(3,2)  # 3,2
print(a)
print(a.shape)

[[ 8  9 10]
 [11 12 13]]
(2, 3)
[[ 8  9]
 [10 11]
 [12 13]]
(3, 2)


In [37]:
import numpy as np
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [38]:
import numpy as np
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[1,3])

6


In [39]:
import numpy as np
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [40]:
import numpy as np
a=np.linspace(1,3,10)
print(a)
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]
3.0
1.0
20.0
2.0


In [49]:
import numpy as np
a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))
print(np.std(a))
print(np.std(a) ** 2)
print(np.median(a))
print(np.mean(a))


[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056
1.6666666666666665
3.0
3.0


In [50]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x+y)

[[ 2  4  6]
 [ 6  8 10]]


In [51]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)

[[0 0 0]
 [0 0 0]]


In [52]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x*y)

[[ 1  4  9]
 [ 9 16 25]]


In [53]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x/y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [56]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))
#print(np.hstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]


In [57]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
#print(np.vstack((x,y)))
print(np.hstack((x,y)))

[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [58]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]


In [59]:
a= np.array([1,2,3])
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692]


In [63]:
a= np.array([1,2,3,10])
print(np.log(a))

[0.         0.69314718 1.09861229 2.30258509]


In [64]:
a= np.array([1,2,3,10])
print(np.log10(a))

[0.         0.30103    0.47712125 1.        ]


In [65]:
a  =np.array([[12,45,89],[67,90,34]])
print(a.sum(axis =0)) 
print("******")
print(a.sum(axis = 1))

[ 79 135 123]
******
[146 191]


In [66]:
a  =np.array([[12,45,89],[45,90,34]])
print(a == 45)

[[False  True False]
 [ True False False]]


In [67]:
a  =np.array([[12,45,89],[45,90,34]])
print(a >= 45)

[[False  True  True]
 [ True  True False]]


In [69]:
# increase one dimention for Every  new axis
a = np.arange(6)  # 1 D
print(a.shape)
print(a)
print(a.ndim,"D")
a2 = a[np.newaxis, :]
print("****")
print(a2.shape)
print(a2)
print(a2.ndim,"D")

(6,)
[0 1 2 3 4 5]
1 D
****
(1, 6)
[[0 1 2 3 4 5]]
2 D


In [70]:
a2 = a[np.newaxis, :]   # 2D
print("****")
print(a2.shape)
print(a2)
print(a2.ndim,"D")
a3 = a2[np.newaxis, :]   # 3D
print("****")
print(a3.shape)
print(a3)
print(a3.ndim,"D")

****
(1, 6)
[[0 1 2 3 4 5]]
2 D
****
(1, 1, 6)
[[[0 1 2 3 4 5]]]
3 D


In [72]:
a = np.zeros((5,4)) #
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [73]:
a = np.ones((5,4)) #
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [74]:
a = np.full((5,4),7) #
print(a)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [77]:
a = np.empty(2)
print(a)

[4.24399158e-314 2.12199579e-313]


In [78]:
b = np.empty(2)
print(b)

[4.24399158e-314 2.12199579e-313]


In [80]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(arr)
arr.sort()
print(arr)


[2 1 5 3 7 4 6 8]
[1 2 3 4 5 6 7 8]


In [82]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(arr)
print(np.sort(arr))
print(arr)


[2 1 5 3 7 4 6 8]
[1 2 3 4 5 6 7 8]
[2 1 5 3 7 4 6 8]


In [84]:
a = np.array([[13,4,34],[9,45,-34]])
print(np.argsort(a))

[[1 0 2]
 [2 0 1]]
